### ISSUE TITLE
wget command can be downloaded, but curl command is not downloaded

### ISSUE THREAD

**Issue by sanshengshui** [apache/mina-ftpserver#29]
As follows: 
<img width="1328" alt="image" src="https://github.com/apache/mina-ftpserver/assets/23117382/f9ca49e7-6ebb-4ffc-9cba-6e190c787dd5">

pom.xml:
```xml
<!--ftp-->
<dependency>
  <groupId>org.apache.ftpserver</groupId>
  <artifactId>ftpserver-core</artifactId>
  <version>1.1.1</version>
</dependency>
```

**Comment by elecharny** [comment]
Hi,

have you tried with ftpserver 1.1.4?

**Comment by sanshengshui** [comment]
Ok, I'll try
By the way, what's the difference between these two versions？

**Comment by elecharny** [comment]
1.1.2: https://issues.apache.org/jira/projects/FTPSERVER/versions/12340451
1.1.3 and 1.1.4 were mainly bumping up some dependencies.

I'd just like to know if you still have the issue with a maintained version, in order to investigate it with the latest code base.

thanks!

**Comment by sanshengshui** [comment]
Just upgraded to version 1.1.4

Here's what happens when you download with curl:
```bash
➜  Downloads curl -u 0297XfYHmj:Cbr3QqJC -o ocpp.tar.gz ftp://f1.iot17.com:8183/1698304726c2bcfc8265c.tar.gz -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 198.19.10.106:8183...
* Connected to f1.iot17.com (198.19.10.106) port 8183 (#0)
< 220 Service ready for new user.
> USER 0297XfYHmj
< 331 User name okay, need password for 0297XfYHmj.
> PASS Cbr3QqJC
< 230 User logged in, proceed.
> PWD
< 257 "/" is current directory.
* Entry path is '/'
* Request has same path as previous transfer
> EPSV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Passive Mode (|||13005|)
*   Trying 198.19.10.106:13005...
* Connecting to 198.19.10.106 (198.19.10.106) port 13005
* Connected to f1.iot17.com (198.19.10.106) port 8183 (#0)
> TYPE I
< 200 Command TYPE okay.
> SIZE 1698304726c2bcfc8265c.tar.gz
< 213 16483570
> RETR 1698304726c2bcfc8265c.tar.gz
  0 15.7M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< 150 File status okay; about to open data connection.
* Maxdownload = -1
* Getting file with size: 16483570
  0 15.7M    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0{ [0 bytes data]
  0 15.7M    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0* transfer closed with 16483570 bytes remaining to read
  0 15.7M    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 16483570 bytes remaining to read
```
What are the possible reasons? 😖

**Comment by elecharny** [comment]
Can you check if you have any log on the FtpServer side?

More specifically, any log containing the string "Exception during data transfer, closing data connection socket".

**Comment by sanshengshui** [comment]
The error message is as follows:

```
2023-10-26 16:41:01.018|TID:N/A|WARN |org.apache.ftpserver.impl.IODataConnectionFactory|createDataSocket|351|pool-18-thread-594| FtpDataConnection.getDataSocket()
java.net.SocketTimeoutException: Accept timed out
        at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
        at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
        at org.apache.ftpserver.impl.IODataConnectionFactory.createDataSocket(IODataConnectionFactory.java:329)
        at org.apache.ftpserver.impl.IODataConnectionFactory.openConnection(IODataConnectionFactory.java:231)
        at com.tuya.sftp.protocol.gateway.service.protocol.command.RetrCommand.execute(RetrCommand.java:74)
        at org.apache.ftpserver.impl.DefaultFtpHandler.messageReceived(DefaultFtpHandler.java:211)
        at org.apache.ftpserver.listener.nio.FtpHandlerAdapter.messageReceived(FtpHandlerAdapter.java:62)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:1015)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
        at org.apache.ftpserver.listener.nio.FtpLoggingFilter.messageReceived(FtpLoggingFilter.java:85)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
        at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:106)
        at org.apache.mina.filter.logging.MdcInjectionFilter.filter(MdcInjectionFilter.java:162)
        at org.apache.mina.filter.util.CommonEventFilter.messageReceived(CommonEventFilter.java:84)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
        at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:418)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:257)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
        at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:106)
        at org.apache.mina.core.session.IoEvent.run(IoEvent.java:89)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:763)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:755)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:695)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by elecharny** [comment]
Ok, this is clearly not a problem in MINA FTP server code. At some point, when the RETR command is received, the following method is called:

```
        at com.tuya.sftp.protocol.gateway.service.protocol.command.RetrCommand.execute(RetrCommand.java:74)
```

then it tries to open a connection to a remote peer which fails (the top of the stack trace).

I suggest you ask the third party (tuya.com) about what's going on there.

**Comment by elecharny** [comment]
Some question:
* the fact the socket times out drives me to think it's more like a configuration issue on your side than a problem in the code. Can you check that?
* Which product are you using? Is it a tuya.com API based lib?

**Comment by sanshengshui** [comment]
I am an employee of tuya.com and am trying to set up an ftp service using FTP-server

I'll keep trying to figure out what caused it

Whether wget enters epsv mode and curl defaults to pasv mode

**Comment by elecharny** [comment]
Ok, so can you provide the code associated with om.tuya.sftp.protocol.gateway.service.protocol.command.RetrCommand?

**Comment by sanshengshui** [comment]
I made a preliminary determination that curl went to epsv mode by default.
The curl command is as follows:

```
➜  ~ curl --ftp-pasv -u 02982C3LaV:TjTv7Swb -O ftp://f1.iot17.com:8183/1698304726c2bcfc8265c.tar.gz -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 198.19.10.106:8183...
* Connected to f1.iot17.com (198.19.10.106) port 8183 (#0)
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0< 220 Service ready for new user.
> USER 02982C3LaV
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0< 331 User name okay, need password for 02982C3LaV.
> PASS TjTv7Swb
< 230 User logged in, proceed.
> PWD
< 257 "/" is current directory.
* Entry path is '/'
* Request has same path as previous transfer
> EPSV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Passive Mode (|||13017|)
*   Trying 198.19.10.106:13017...
* Connecting to 198.19.10.106 (198.19.10.106) port 13017
* Connected to f1.iot17.com (198.19.10.106) port 8183 (#0)
> TYPE I
< 200 Command TYPE okay.
> SIZE 1698304726c2bcfc8265c.tar.gz
< 213 16483570
> RETR 1698304726c2bcfc8265c.tar.gz
  0 15.7M    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0< 150 File status okay; about to open data connection.
* Maxdownload = -1
* Getting file with size: 16483570
  0 15.7M    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0{ [0 bytes data]
* transfer closed with 16483570 bytes remaining to read
  0 15.7M    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 16483570 bytes remaining to read
```

When I use wget, pasv mode works fine

**Comment by sanshengshui** [comment]
One way to cheat is: Through what configuration can the client only go to PASV mode

**Comment by elecharny** [comment]
@sanshengshui the diff I see is that curl uses ESPV while wget uses PASV. Is that a IPV6 connection?

**Comment by sanshengshui** [comment]
IPV4 connection
